baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"

title = "TravelgateX Documentation"
theme = "docdock"
#themesdir = "../.."

#GoogleAnalytics: "UA-106994170-2"

[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
pre = "<h3>More</h3>"
name = "<i class='fa fa-github'></i> GraphQL Playground"
identifier = "ds"
url = "https://api.travelgatex.com"
weight = 10

#[[menu.shortcuts]]
#name = "<i class='fa fa-camera'></i> Showcases"
#url = "/showcase"
#weight = 11

#[[menu.shortcuts]]
#name = "<i class='fa fa-bookmark'></i> Hugo Documentation"
#identifier = "hugodoc"
#url = "https://gohugo.io/"
#weight = 20

#[[menu.shortcuts]]
#name = "<i class='fa fa-bullhorn'></i> Credits"
#url = "/credits"
#weight = 30


#Elade HOME

[params]

############## docdock params

#editURL = "https://github.com/vjeantet/hugo-theme-docdock/edit/master/exampleSite/content/"
editURL = "https://github.com/travelgateX/documentation-site/edit/master/content/"
showVisitedLinks = true # default is false
themeStyle = "flex" # "original" or "flex" # default "original"
themeVariant = "blue" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false

discourseUrl = "http://discourse.travelgatex.com/"

############## docdock params

  
  #custom_css = ["css/blue.css"]

  # Meta
  author = "tgX ByXTG"
  description = "All you want and need to know about travelgateX state-of-the-art GraphQL APIs. Start your next travel project here."
  email = "tech@travelgatex.com"
  # Navigation
  [params.navigation]
    brand = '<img src="images/header-logo.png"/>'
    home = "Home"
    work = "Our APIs"
    testimonials = "Testimonials"
    services = "Services"
    about = "About"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    [[menu.prepend]]
      url = "http://api.travelgatex.com"
      name = "Playground <i title='Play &rarr;' class='icon-control-play'></i>"
      weight = 10

    # postpended links
    [[menu.postpend]]
     url = "http://discourse.travelgatex.com/"
     name = "Community"
     weight = 10
  
  # Hero section
  [params.hero]
    title = "Finally, a travel API you'll&nbsp;&nbsp;<i title='love &#9825;' class='icon-heart'></i>"
    subtitle = "At XTG, we've integrated 100s of travel APIs. This is why we've decided to build the first travel API focused on<br/><strong>Developer eXperience</strong>.<p>Welcome to <strong>ConnectX</strong>, the world's most _advanced_ and _disruptive_ <strong>GraphQL</strong> based Travel API.</p>"
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Getting Started"
    description = "The inner workings of our APIs. Search, book, retrieve stats and much more."
    url = "getting-started/"
    button = "Go Get Started"
    icon = "icon-fire"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Learning GraphQL"
    description = "Get to know GraphQL, tutorials, resources. All you need to master the tech."
    url = "learning-graphql/"
    button = "Go Learn"
    icon = "icon-book-open"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "API Playground"
    description = "Don't take it from us, try our ready-made real life examples to see it for yourself."
    url = "https://api.travelgatex.com/"
    class = "external"
    button = "Go Play"
    icon = "icon-control-play"
    img = "img_10.jpg"
    target = "_blank"

  #[[params.intro.item]]
    #title = "Community"
    #description = "You're never alone. Join our growing community."
    #url = "http://discourse.travelgatex.com/"
    #button = "Join the Discussion"
    #icon = "icon-rocket"
    #img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section
  [params.work]
    enable = true
    title = "Our APIs"
    description = "We're true believers in the <strong>API first</strong> philosophy. Anything you can do on any of our sites and tools you can also do using the GraphQL API."
    footertext = 'APIs Made With &#9825; For Developers &amp; By Developers'

    [[params.work.row]]
      url = "api/connectx/hotel/"
      img = "work_1.jpg"
      alt = "Image2"
      title = "Hotel Search & Book API"
      subtitle = "Search & Book on more than 400 hotel suppliers, seamlessly!"

    [[params.work.row]]
      url = "api/connectx/flight/"
      img = "work_2.jpg"
      alt = "Image2"
      title = "Flight Search & Book API"
      subtitle = "NDC certified search & book API with many traditional, low cost and NDC carriers + GDS."

    [[params.work.row]]
      url = "api/stats/"
      img = "work_3.jpg"
      alt = "Image3"
      title = "Stats API"
      subtitle = "Real-time information about all your requests: totals, response times, status and more."

    [[params.work.row]]
      url = "api/insights/"
      img = "work_4.jpg"
      alt = "Image4"
      title = "Insights API"
      subtitle = "Get detailed Business Intelligence data such as ratios per hotel, country, market and many more."

    [[params.work.row]]
      url = "api/mappea/"
      img = "work_5.jpg"
      alt = "Image5"
      title = "Mappea API"
      subtitle = "Map and de-dupe hotels using our unique collaborative mapping API. More than 19 Million hotels."

    [[params.work.row]]
      url = "api/account/"
      img = "work_6.jpg"
      alt = "Image6"
      title = "Account API"
      subtitle = "Create & Manage your users, connections and API keys. Use this API to keep track of your account."

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "Testimonials"
    description = "See what our Beta Testers &amp; Early Adopters have to say.<br/>Learn. Test. Decide."

    [[params.testimonials.item]]
      quote = "&ldquo;We've started working with the legacy API 4 years ago. When they've told us they were developing a new API we _had to be a part of it_. Our developers loved it, and best of all, we can now deliver all the integrations business requires us&rdquo;"
      person = 'Dani Martin, Architect <a href="http://www.guestincoming.com/" target="_blank">Guest Incoming</a> <span class="subtext">CTO</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "&ldquo;We have started working with ConnectX when it was still under development. Firstly, it was a bit hard since we didn't know GraphQL and the structure kept changing, but in every iteration it got better and more stable. Nowadays, we're happy to have started so early. We're connected to every major Meta Search, respond in less than 1 second and the service is very stable!&rdquo;"
      person = 'Vishal, Senior Developer <a href="http://www.trulytravel.com//" target="_blank">Truly Travel</a> <span class="subtext">Tech Lead</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;I met these guys last year in Berlin and they've told us about the project, it was still at that stage, project only. But as soon as they've told me about their plans I knew they were on to something and I felt I _couldn't miss out_! It's by far the most advanced API I've seen in travel and in general, I'm impresses by the simplicity and speed of the API. Congrats guys!&rdquo;"
      person = 'Vitali, Senior Developer <a href="http://www.roomertravel.com/" target="_blank">Roomer Travel</a> <span class="subtext">CTO</span>'
      img = "person3.jpg"
      alt = "Person3"
    



  # Services section
  [params.services]
    enable = false
    title = "Services"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.services.item]]
      title = "Brand &amp; Strategy"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Web &amp; Interface"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-layers2"
    [[params.services.item]]
      title = "Photo &amp; Video"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"
      icon = "icon-video2"

      [[params.services.item]]
      title = "CMS &amp; eCommerce"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean"      
      icon = "icon-monitor"

  # About section
  [params.about]
    enable = false
    title = "About"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.about.item]]
      name = "Jean Smith"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Rob Smith"
      position = "Web Developer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Larry Ben"
      position = "Web Designer"
      description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]      

  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Live Suppliers"
      icon = "icon-briefcase"
      from = 0
      to = 623
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Searches per Minute"
      icon = "icon-speedometer"
      from = 0
      to = 623456
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Bookings Per Day"
      icon = "icon-wallet"
      from = 0
      to = 23412
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 132
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = false
    map = false
    title = "Get in touch"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "5555 Love Paradise 56 New Clity 5655, <br> Excel Tower United Kingdom"],
        ["icon-phone", "(123) 465-6789"],
        ["icon-envelope", "info@freehtml5.co"],
        ["icon-globe", '<a href="http://freehtml5.co/" target="_blank">freehtml5.co</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; TravelgateX 2017. All Rights Reserved.<br/>An <a title="XTG" href="https://www.xmltravelgate.com/">XTG</a> Brand.'